// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(e,t,s){var n=jQuery,o=n(this),i=(n(".ws_list",s),{position:"absolute",left:0,top:0,width:"100%",height:"100%",transform:"translate3d(0,0,0)"}),d=n("<div>").addClass("ws_effect").css(i).css("overflow","hidden").appendTo(s.parent());this.go=function(s,a){var r=n(t.get(s)),f={width:r.width(),height:r.height()};if(r=r.clone().css(i).css(f).hide().appendTo(d),!e.noCross){var c=n(t.get(a)).clone().css(i).css(f).appendTo(d);c.fadeOut(e.duration,function(){c.remove()})}r.fadeIn(e.duration,function(){o.trigger("effectEnd"),r.remove()})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:12*100,delay:22*100,width:960,height:360,autoPlay:true,playPause:true,stopOnHover:false,loop:false,bullets:true,caption:true,captionEffect:"slide",controls:true,onBeforeStep:0,images:0});